

export enum ACTION_TYPES {
    
    LOGIN = "LOGIN",
    SET_MUSIC_DETAIL  = "SET_MUSIC_DETAIL",
    TOGGLE_LEFT_SIDEBAR  = "TOGGLE_LEFT_SIDEBAR",
    SET_PREPARE_PLAYLIST  = "SET_PREPARE_PLAYLIST",
    FETCH_FAVORITES_SONG  = "FETCH_FAVORITES_SONG",
SET_PLAYER_SLATS  = "SET_PLAYER_SLATS"

    
}
